name: Publish release
run-name: Publish release

on:
  workflow_call:
    inputs:
      pre_release:
        type: boolean
        default: false
        required: false
      archive_name:
        type: string
        required: true
      files:
        type: string
        required: true

jobs:
  Version:
    uses: HornaHomeLab/Actions_Releases/.github/workflows/Check_version.yaml@main

  Tag:
    needs: Version
    uses: HornaHomeLab/Actions_Releases/.github/workflows/Create_tag.yaml@main
    with:
      version_tag: ${{ needs.Version.outputs.version_tag }}
      tag_reference_exist: ${{ needs.Version.outputs.tag_reference_exist }}

  Release:
    needs: [Version, Tag]
    uses: HornaHomeLab/Actions_Releases/.github/workflows/Create_release.yaml@main
    with:
      version_tag: ${{ needs.Version.outputs.version_tag }}
      pre_release: ${{ inputs.pre_release }}

  Assets:
    needs: [Version, Release]
    uses: HornaHomeLab/Actions_Releases/.github/workflows/Create_asset.yaml@main
    with:
      archive_name: ${{ inputs.archive_name }}
      release_id: ${{ needs.Release.outputs.release_id }}
      version_tag: ${{ needs.Version.outputs.version_tag }}
      files_to_archive: ${{ inputs.files }}
