name: Remove release
run-name: Remove release

on:
  workflow_call:

env:
  success_ico: ":white_check_mark:"
  failure_ico: ":x:"
  cancel_ico: ":no_entry_sign:"

jobs:
  Version:
    runs-on: ${{ vars.DEFAULT_RUNNER }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Tag
        id: file
        run: |
          tag=$(grep '##### version:' './README.md' | awk -F: '{print $2}' | tr -d '[:blank:]')

          if [ -z "$tag" ]; then
            echo "Can not find verion in ./README.md"
            echo "# ${{ env.failure_ico }} Cannot find version in ./README.md ${{ env.failure_ico }}" >> $GITHUB_STEP_SUMMARY
            exit 1
          fi

          echo "tag_name=$tag" >> $GITHUB_OUTPUT

      - name: Check if Release ${{ steps.file.outputs.tag_name }} exists
        id: release-check
        run: |
          echo "release_id=$(
            curl -L -s --fail-with-body \
              -X GET \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              --url https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ steps.file.outputs.tag_name }} \
            | jq .id)" >> $GITHUB_OUTPUT

      - name: Remove Release ${{ steps.file.outputs.tag_name }}
        if: steps.release-check.outputs.release_id != 'null'
        run: |
          curl -L -s --fail-with-body \
            -X DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            --url https://api.github.com/repos/${{ github.repository }}/releases/${{ steps.release-check.outputs.release_id }}

      - name: Remove Tag ${{ steps.file.outputs.tag_name }} reference
        if: steps.release-check.outputs.release_id != 'null'
        run: |
          curl -L -s --fail-with-body \
            -X DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            --url https://api.github.com/repos/${{ github.repository }}/git/refs/tags/${{ steps.file.outputs.tag_name }}
