name: Create release

on:
  workflow_call:
    inputs:
      version_tag:
        type: string
        required: true



jobs:
  Create_Release:
    runs-on: container
    steps:
      - name: Check if Release ${{ inputs.version_tag }} exists
        id: release-check
        run: |
          echo "release_id=$(
            curl -L -s --fail-with-body \
              -X GET \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              --url https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ inputs.version_tag }} \
            | jq .id)" >> $GITHUB_OUTPUT

      - name: Remove Release ${{ inputs.version_tag }}
        if: steps.release-check.outputs.release_id != 'null'
        run: |
          curl -L -s --fail-with-body \
            -X DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            --url https://api.github.com/repos/${{ github.repository }}/releases/${{ steps.release-check.outputs.release_id }} 