name: Create tag

on:
  workflow_call:
    inputs:
      version_tag:
        type: string
        required: true
      tag_reference_exist:
        type: string
        required: true

jobs:
  Remove:
    runs-on: container
    steps:
      - name: Remove Tag ${{ inputs.version_tag }} reference
        if: ${{ inputs.tag_reference_exist == 'true' }}
        run: |
          curl -L -s --fail-with-body \
            -X DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            --url https://api.github.com/repos/${{ github.repository }}/git/refs/tags/${{ inputs.version_tag }} 
